apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-qylw
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/qijing/release-e2e-pyxis-tenant/appstudio/dc-metro-map-qylw@sha256:c17f0cde4983bda59a5bd3d0b1eb3a964dfadf835afecb6b7620e038749e8406
        name: my-nodejs
        resources: {}
status: {}
