apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-ilbr
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/qijing/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-ilbr@sha256:1eec3908744e666f7a8b330012330659143aa666a813e3a98f7484ff93494eed
        name: container-image
        resources: {}
status: {}
